- name: Create three subdirectories
  hosts: localhost
  tasks:
    - name: creating kubernetes directory
      file:
        path: /tmp/master01/pki/etcd
        state: directory
        mode: "0755"

    - name: creating kubernetes directory
      file:
        path: /tmp/master01/pki/etcd
        state: directory
        mode: "0755"

- name: Copy certs to controller
  hosts: etcd01
  tasks:
    - name: Copy apiserver-etcd-client.crt
      fetch:
        src: /etc/kubernetes/pki/apiserver-etcd-client.crt
        dest: /tmp/master01/pki/
        flat: yes

    - name: copy apiserver-etcd-client.key
      fetch:
        src: /etc/kubernetes/pki/apiserver-etcd-client.key
        dest: /tmp/master01/pki/
        flat: yes

    - name: copy ca.crt
      fetch:
        src: /etc/kubernetes/pki/etcd/ca.crt
        dest: /tmp/master01/pki/etcd/
        flat: yes

- name: pki directory
  hosts: master01
  vars:
    HOST0: 192.168.40.60
    HOST1: 192.168.40.61
    HOST2: 192.168.40.62
  become: yes
  tasks:
    - name: creating kubernetes directory
      file:
        path: /etc/kubernetes
        state: directory
        mode: '0755'

    - name: Create directory sub1
      copy:
        src: /tmp/master01/pki
        dest: /etc/kubernetes/
        mode: '0755'

    - name: change pki groupe own
      file:
        path: /etc/kubernetes/pki
        owner: root
        group: root
        mode: '0755'

    - name: pull images
      become: yes
      command:
        cmd: kubeadm config images pull

    - name: Creating kubeadm configuracion file
      copy:
        content: |
          ---
          apiVersion: kubeadm.k8s.io/v1beta3
          kind: InitConfiguration
          nodeRegistration:
            kubeletExtraArgs:
              volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
          ---
          apiVersion: kubeadm.k8s.io/v1beta3
          kind: ClusterConfiguration
          kubernetesVersion: stable
          networking:
            podSubnet: 192.168.0.0/16
          controlPlaneEndpoint: "192.168.40.51:6443"
          etcd:
            external:
              endpoints:
                - https://192.168.40.60:2379
                - https://192.168.40.61:2379
                - https://192.168.40.62:2379
              caFile: /etc/kubernetes/pki/etcd/ca.crt
              certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
              keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
          clusterName: lab-cluster
          controllerManager:
            extraArgs:
              flex-volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
        dest: /home/securiport/kubeadm-config.yaml
     #   backup: yes

    - name: kubeadm init --config kubeadm-config.yaml
      become: yes
      shell: kubeadm init --config /home/securiport/kubeadm-config.yaml --upload-certs >> first_master_joined.txt

    - name: creating .kube directory
      become: yes
      file:
        path: $HOME/.kube
        state: directory
        owner: securiport
        group: securiport
        mode: '0755'

    - name: copy file admin.conf
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
        owner: securiport
        group: securiport
        mode: '0755'

    - name: Creating calico configuracion file
      become: yes
      set_fact:
        calico_content: |
          # Source: https://docs.projectcalico.org/manifests/custom-resources.yaml
          apiVersion: operator.tigera.io/v1
          kind: Installation
          metadata:
            name: default
          spec:
            # Configures Calico networking.
            calicoNetwork:
              # Note: The ipPools section cannot be modified post-install.
              ipPools:
              - blockSize: 26
                cidr: 192.168.0.0/16
                encapsulation: VXLANCrossSubnet
                natOutgoing: Enabled
                nodeSelector: all()
              flexVolumePath: /opt/libexec/kubernetes/kubelet-plugins/volume/exec/

    - name: Creating calico configuracion file on home directory
      become: yes
      copy:
        content: "{{ calico_content }}"
        dest: /home/securiport/calico.yaml

    - name: Downloading calico using get_url
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/custom-resources.yaml
        dest: /home/securiport/

    - name: install Tigera
      become: yes
      command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/tigera-operator.yaml

    - name: install Calico
      become: yes
      command: kubectl create -f /home/securiport/custom-resources.yaml